sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      env:
         - NAME="gcc-4.8"

    # works on Precise and Trusty
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - NAME="gcc-5.4"
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - NAME="gcc-6.3"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - compiler: clang
      env:
        - NAME="clang-3.5"

    - os: osx
      osx_image: xcode8
      env:
        - NAME="xcode-8.0"

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     brew update;
   else
     eval "${MATRIX_EVAL}" &&
     sudo apt-get update -qq &&
     wget https://github.com/xtalopt/xtalopt-dependencies/releases/download/1.0/qwt_6.1.3-2-Ubuntu14.04-gcc4.8.4.deb;
     wget https://github.com/xtalopt/xtalopt-dependencies/releases/download/1.0/rdkit-dev-2017.9.18-Ubuntu14.04-gcc4.8.4.deb;
     wget https://github.com/xtalopt/xtalopt-dependencies/releases/download/1.0/rdkit-runtime-2017.9.18-Ubuntu14.04-gcc4.8.4.deb;
     wget https://github.com/xtalopt/xtalopt-dependencies/releases/download/1.0/libboost1.62-Ubuntu14.04-gcc4.8.4.deb;
   fi

install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     brew upgrade git cmake;
     brew install qt5 qwt libssh eigen;
   else
     sudo apt-get install -qq qt5-default libeigen3-dev libssh-dev
                              libqt5svg5 lcov;
     sudo dpkg -i qwt_6.1.3-2-Ubuntu14.04-gcc4.8.4.deb;
     sudo dpkg -i rdkit-dev-2017.9.18-Ubuntu14.04-gcc4.8.4.deb;
     sudo dpkg -i rdkit-runtime-2017.9.18-Ubuntu14.04-gcc4.8.4.deb;
     sudo dpkg -i libboost1.62-Ubuntu14.04-gcc4.8.4.deb;
   fi

before_script:
 # For Linux, we have to load the travis-ci display to run the tests even
 # though we don't actually need the display...
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     export CMAKE_FLAGS="$CMAKE_FLAGS -DCMAKE_PREFIX_PATH=/usr/local/opt/qt/" &&
     export CMAKE_FLAGS="$CMAKE_FLAGS -DQWT_INCLUDE_DIR=/usr/local/opt/qwt/lib/qwt.framework/Headers";
   else
     export DISPLAY=:99.0 &&
     sh -e /etc/init.d/xvfb start &&
     sleep 3;
     export CMAKE_FLAGS="$CMAKE_FLAGS -DENABLE_MOLECULAR=ON";
   fi

 - export CMAKE_FLAGS="$CMAKE_FLAGS -DBUILD_INDEPENDENT_PACKAGE=ON"
 - export CMAKE_FLAGS="$CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=install/xtalopt"
 - export CMAKE_FLAGS="$CMAKE_FLAGS -DBUILD_TESTS=ON"
 - mkdir build
 - cd build
 - mkdir install
 - cmake ${CMAKE_FLAGS} ..

script:
 - make -j2
 - ctest --output-on-failure

after_success:
 # For GCC only: capture coverage info, filter out system, print debug info,
 # and upload to codecov
 - if [[ "$NAME" == "gcc-4.8" ]]; then
     lcov --directory . --capture --output-file coverage.info &&
     lcov --remove coverage.info '/usr/*' --output-file coverage.info &&
     lcov --list coverage.info &&
     bash <(curl -s https://codecov.io/bash) ||
     echo "Codecov did not collect coverage reports";
   fi

 # If this is a tag, then zip the install directory, md5sum it, and upload it
 - if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
     if [[ "$NAME" == "gcc-4.8" ]]; then
       echo "Tag detected for gcc-4.8. Installing, zipping installation, and creating md5sum." &&
       make -j2 install &&
       cd install &&
       tar -czvf linux-xtalopt.tgz xtalopt &&
       md5sum linux-xtalopt.tgz > linux-xtalopt.md5;
     elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       echo "Tag detected for osx. Installing, zipping installation, and creating md5sum." &&
       sudo make -j2 install &&
       sudo chown -R travis ./install &&
       cd install/xtalopt &&
       zip -r osx-xtalopt.zip xtalopt.app &&
       md5 osx-xtalopt.zip > osx-xtalopt.md5;
     fi
   else
     echo "Tag not detected. Skipping zip and md5sum.";
   fi

deploy:
  - provider: releases
    file:
      - linux-xtalopt.tgz
      - linux-xtalopt.md5
    skip_cleanup: true
    api_key:
      secure: OV+fiXKG9XW6AHN2p79aFdIiGbkf6ofatJ0QWLzOhtAylrUmKL2rdaQLve64g7DXdzDMuUKXLncXPYdIoPLYau9CvZvejNhGCKH+GDRuUuW1TbivRHEBQvxZCGqH5YGKTRLu8Ip7RNeQo0+3KWT6aed971NVzPV2zgET1okSvDFTJIC+ZyZ6gd2u0WeKPerVgZk9RgF7liIykJnL74mi51IRDslKNNsyXC2fEDwRqCBpO6E2QpxSHnTKmMLy1jdfI+V1bEyqi3Bfc8lRuzbUh5YpxZ0GQlzjWqLosAaIVy07YON3UcPQz6aiXr0PGUXknVLwK2y2Vdo2LV3KGo9o5ahyU2roXThVCyhVRPyYKU+4PdXJPeH3dmOmc25keF9ubWhgvWCExacue7g1ww4cN+yKHAJJOlsHyIaDhS/F72nKad4YVSpLpw0pY29qY8yrEHGYW2YbIP70UL2r70KIBFvsaBBbIrl0N5CnRsmbZkGi0urXgYttfw/ehhgPkDgueONjnGHgqbPSHQ0JpxlOWSy8ghjhYpXTDVaUp54uWZfN7OnqufN5rkCoWA5Q6Qkh8PbiOPNb9IMuzkP1wlxYtVI43vUekeS7+RVtXnowrKb1z/19kCeZrvKuVM18achHwM6uXMbn6IjQLHJqpn21n8tca+6gyWDZGiuYzkceHhQ=
    on:
      repo: xtalopt/XtalOpt
      tags: true
      all_branches: true
      condition: $NAME = "gcc-4.8"

  - provider: releases
    file:
      - osx-xtalopt.zip
      - osx-xtalopt.md5
    skip_cleanup: true
    api_key:
      secure: OV+fiXKG9XW6AHN2p79aFdIiGbkf6ofatJ0QWLzOhtAylrUmKL2rdaQLve64g7DXdzDMuUKXLncXPYdIoPLYau9CvZvejNhGCKH+GDRuUuW1TbivRHEBQvxZCGqH5YGKTRLu8Ip7RNeQo0+3KWT6aed971NVzPV2zgET1okSvDFTJIC+ZyZ6gd2u0WeKPerVgZk9RgF7liIykJnL74mi51IRDslKNNsyXC2fEDwRqCBpO6E2QpxSHnTKmMLy1jdfI+V1bEyqi3Bfc8lRuzbUh5YpxZ0GQlzjWqLosAaIVy07YON3UcPQz6aiXr0PGUXknVLwK2y2Vdo2LV3KGo9o5ahyU2roXThVCyhVRPyYKU+4PdXJPeH3dmOmc25keF9ubWhgvWCExacue7g1ww4cN+yKHAJJOlsHyIaDhS/F72nKad4YVSpLpw0pY29qY8yrEHGYW2YbIP70UL2r70KIBFvsaBBbIrl0N5CnRsmbZkGi0urXgYttfw/ehhgPkDgueONjnGHgqbPSHQ0JpxlOWSy8ghjhYpXTDVaUp54uWZfN7OnqufN5rkCoWA5Q6Qkh8PbiOPNb9IMuzkP1wlxYtVI43vUekeS7+RVtXnowrKb1z/19kCeZrvKuVM18achHwM6uXMbn6IjQLHJqpn21n8tca+6gyWDZGiuYzkceHhQ=
    on:
      repo: xtalopt/XtalOpt
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = "osx"
